spring:
  data:
    cassandra:
      schema-action: create-if-not-exists
      keyspace-name: ks_spring
      username: token
      password: AstraCS:gdZaqzmFZszaBTOlLgeecuPs:edd25600df1c01506f5388340f138f277cece2c93cb70f4b5fa386490daa5d44
datastax:
  astra:
    secure-connect-bundle: /Users/cedricklunven/Downloads/secure-connect-workshops.zip
    #secure-connect-bundle: /workspace/workshop-spring-quarkus-micronaut-cassandra/secure-bundle-workshops.zip
      
