micronaut:
  application:
    name: lab4-micronaut
  server:
    port: 8082
    cors:
      enabled: true
cassandra:
  default:
    basic:
      request:
        timeout: 5 seconds
      session-keyspace: ks_micronaut
      cloud:
        secure-connect-bundle: /workspace/workshop-spring-quarkus-micronaut-cassandra/secure-bundle-workshops.zip
    advanced:
      auth-provider:
        class: PlainTextAuthProvider
        username: token
        password: ${ASTRA_DB_APP_TOKEN}
      connection:
        init-query-timeout: 5 seconds          
        set-keyspace-timeout: 5 seconds
      control-connection.timeout: 5 seconds



